### PR TITLE
Add HiLetgo ILI9341 SPI 240x320 display

### PR DESCRIPTION
**Pull request by Palomino34**

### CODE REVIEW

**Review by gus-ghielec — APPROVED** [review]

**Comment by MBNSoftware** [comment]
Very nice code ! 😃

**Comment by gus-ghielec** [comment]
Thanks to you 😎

**Comment by MBNSoftware** [comment]
Btw, I don't see any pin assigned to backlight in your driver. 
Does that mean that your display does not have one ?

**Comment by Palomino34** [comment]
Because we wanted ILI9341 same as N18 and native lcd  which don't include backlight in their constructors.

control backlight is not in driver for now.

**Comment by MBNSoftware** [comment]
Ok. I understand.

Thank you !

**Pull request merged**
